// Auto-generated by tools/generate-versions.js
// Do not edit manually.
export const archivedVersions = [
  "v0.8",
  "v0.9"
] as const;
export type ArchivedVersion = typeof archivedVersions[number];
